apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: coop
  name: coop
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coop
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: coop
    spec:
      containers:
      - image: everyyy/coop:83b956550ae5e8d1704748181c8c3083eaa8688c
        name: coop
        ports:
        - containerPort: 8000
        resources: {}
status: {}
