apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: coop
  name: coop
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: coop
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: coop
    spec:
      containers:
      - image: everyyy/coop:ddf1983e446e0d36ee49abbb111e817eecd24695
        name: coop
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
status: {}
