apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: coop
  name: coop
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coop
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: coop
    spec:
      containers:
      - image: everyyy/coop:7a2dbf1f388a4ce78370c88e2f1c8e898b74b4ec
        name: coop
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
status: {}
